; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = espidf
build_flags = -Iinclude -ggdb

monitor_speed = 115200
upload_protocol = esp-prog
debug_tool = esp-prog
debug_init_break = tbreak setup
check_tool = cppcheck
check_flags = --enable=all --addon=cppcheck-config/misra.json --std=c11 --language=c  --suppress=*:*.pio/build/upesy_wroom/config/*
